services:
  web:
    build: .
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "81:80"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
      - phpmyadmin

  db:
    image: mariadb:10.8.2
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
    ports:
      - "8889:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
      - "8890:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: test

volumes:
  mysql:
